core/urls.py
from django.urls import path
from core import views

app_name = "core"


urlpatterns = [
    # Common
    path("", views.HomeView.as_view(), name="home"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("contact/", views.ContactView.as_view(), name="contact"),
    path("news/", views.NewsView.as_view(), name="news"),
    path("shop/", views.ShopView.as_view(), name="shop"),
    # User
    path("user/profile/", views.ProfileView.as_view(), name="profile"),
    path("user/dashboard/", views.DashboardView.as_view(), name="dashboard"),
    path("user/settings/", views.SettingsView.as_view(), name="settings"),
    # Authentication urls
    path("user/login/", views.LoginView.as_view(), name="login"),
    path("user/signup/", views.SignupView.as_view(), name="signup"),
    path("user/logout/", views.LogoutView.as_view(), name="logout"),
    # Password Reset
    path("user/password_reset/", views.PasswordResetView.as_view(), name="password_reset"),
    path("user/password_reset/done/", views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("user/reset/<uidb64>/<token>/", views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("user/reset/done/", views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    # Password Change
    path("user/password_change/", views.PasswordChangeView.as_view(), name="password_change"),
    path("user/password_change/done/", views.PasswordChangeDoneView.as_view(), name="password_change_done"),
    # Product
    path("product/<int:pk>/detail/", views.ProductDetailView.as_view(), name="product_detail"),
    path("product/category/", views.CategoryListView.as_view(), name="category_list"),
    path("product/category/<int:pk>/product/", views.ProductListByCategory.as_view(), name="product_by_category"),
    # Product Review
    path("product/<int:pk>/review/", views.ProductReviewAddView.as_view(), name="add_product_review"),
    # Wishlist
    path("wishlist/", views.WishlistListView.as_view(), name="wishlist_list"),
    path("wishlist/create/", views.WishlistCreateView.as_view(), name="wishlist_create"),
    path("wishlist/<int:pk>/", views.WishlistDetailView.as_view(), name="wishlist_detail"),
    path("wishlist/add/product/<int:product_pk>/", views.AddToWishlist.as_view(), name="add_to_wishlist"),
    path("wishlist/remove/product/<int:product_pk>/", views.AddToWishlist.as_view(), name="remove_from_wishlist"),
    # Cart
    path("cart/", views.CartView.as_view(), name="cart"),
    path("cart/add/", views.AddToCartView.as_view(), name="cart_add"),
    path("cart/checkout/", views.CheckoutView.as_view(), name="cart_checkout"),
    path("cart/payment/", views.PaymentView.as_view(), name="cart_payment"),
    # Payment
    path("payment/", views.PaymentListView.as_view(), name="payment_list"),
    # Order
    path("order/history/", views.OrderHistoryView.as_view(), name="order_history"),
    path("order/", views.OrderView.as_view(), name="order"),
    path("order/<str:pk>/", views.OrderDetailView.as_view(), name="order_detail"),

]

emart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path('accounts/', include('allauth.urls')),
    path("admin/", admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.db.models import Sum, F, Q, Avg


class User(AbstractUser):
    pass


# ======================================================== #
# Global Variables                                         #
# ======================================================== #

USER = get_user_model()

# ======================================================== #
# Abstract Models                                          #
# ======================================================== #
class TimeStamp(models.Model):
    status = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Location(TimeStamp, models.Model):
    longitude = models.FloatField()
    lattitude = models.FloatField()

    def __str__(self):
        return f"{self.longitude},{self.lattitude}"


class Address(TimeStamp, models.Model):
    building_name = models.CharField(max_length=120)
    place = models.CharField(max_length=64)
    street = models.CharField(max_length=64)
    city = models.CharField(max_length=64)
    district = models.CharField(max_length=64)
    state = models.CharField(max_length=64)
    country = models.CharField(max_length=64)
    post_office = models.CharField(max_length=64)
    post_code = models.CharField(max_length=64)
    location = models.ForeignKey(
        "Location", on_delete=models.SET_NULL, null=True, blank=True
    )

    def __str__(self):
        return f"{self.building_name}\n{self.place}\n{self.district}\n{self.state} - {self.post_code}"

    @staticmethod
    def get_obj_for_profile(request, **kwargs):
        user = request.user
        obj = Address.objects.filter(profile__user=user, status=True, **kwargs).first()
        return obj


class Feedback(TimeStamp, models.Model):
    name = models.CharField(max_length=60)
    email = models.EmailField(max_length=60)
    subject = models.CharField(max_length=120, default="I want to know more.")
    message = models.TextField(max_length=500)
    is_replied = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.name}"


class FeedbackReply(TimeStamp, models.Model):
    feedback = models.OneToOneField(Feedback, on_delete=models.CASCADE)
    reply = models.TextField(max_length=500)
    user = models.ForeignKey(USER, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"{self.feedback.subject}"


# ======================================================== #
# User Related Models                                      #
# ======================================================== #
class Profile(TimeStamp, models.Model):
    class GenderChoices:
        male = "m"
        female = "f"
        transgender = "t"

    class AccountTypeChoices:
        customer = "customer"
        administrator = "admin"

    GENDER_CHOICES = (
        (GenderChoices.male, "Male"),
        (GenderChoices.female, "Female"),
        (GenderChoices.transgender, "Transgender"),
    )

    ACCOUNT_TYPE_CHOICES = (
        ("Customer", AccountTypeChoices.customer),
        ("Administrator", AccountTypeChoices.administrator),
    )

    first_name = models.CharField(max_length=32)
    last_name = models.CharField(max_length=32)
    gender = models.CharField(max_length=12, choices=GENDER_CHOICES)
    address = models.ForeignKey(
        Address, on_delete=models.SET_NULL, null=True, blank=True
    )
    image = models.ImageField(
        upload_to="user/profile/image", default="default/user.png"
    )
    account_type = models.CharField(
        max_length=16,
        choices=ACCOUNT_TYPE_CHOICES,
        default=AccountTypeChoices.customer,
    )
    user = models.OneToOneField(USER, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    is_loyal = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    @staticmethod
    def get_obj(request, **kwargs):
        user = request.user
        obj = Profile.objects.filter(user=user, status=True, **kwargs).first()
        return obj


# ======================================================== #
# Product Related Models                                   #
# ======================================================== #
class CategoryModel(TimeStamp, models.Model):
    name = models.CharField(max_length=48)
    image = models.ImageField(
        upload_to="category/image/", default="default/category.png"
    )
    parent = models.ForeignKey("self", on_delete=models.SET_NULL, null=True, blank=True)
    user = models.ForeignKey(USER, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse("product:category_detail", kwargs={"pk": self.pk})


class UnitModel(TimeStamp, models.Model):
    name = models.CharField(max_length=16)
    symbol = models.CharField(max_length=16)
    convertion_rate = models.FloatField()
    secondary = models.ForeignKey(
        "self", on_delete=models.SET_NULL, null=True, blank=True
    )
    user = models.ForeignKey(USER, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse("product:unit_detail", kwargs={"pk": self.pk})


class ProductModel(TimeStamp, models.Model):
    name = models.CharField(max_length=120)
    description = models.TextField(max_length=500)
    price = models.FloatField()
    image = models.ImageField(upload_to="product/image/", default="default/product.png")
    category = models.ForeignKey(
        CategoryModel, on_delete=models.SET_NULL, null=True, blank=True
    )
    unit = models.ForeignKey(
        UnitModel, on_delete=models.SET_NULL, null=True, blank=True
    )
    user = models.ForeignKey(USER, on_delete=models.CASCADE)

    # products = ProductManager()

    def __str__(self) -> str:
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse("product:product_detail", kwargs={"pk": self.pk})

    def get_review(self):
        reviews = (
            self.reviewmodel_set.annotate(
                product_review=F("rating")
            )
            .aggregate(Avg("product_review"))
            .get("product_review__avg")
        )

        return reviews


class ReviewModel(TimeStamp, models.Model):
    product = models.ForeignKey(ProductModel, on_delete=models.CASCADE)
    rating = models.FloatField()
    comment = models.TextField(max_length=250)
    user = models.ForeignKey(USER, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f"{self.user} ({self.rating})"

    def get_absolute_url(self):
        return reverse("product:review_detail", kwargs={"pk": self.pk})


class WishlistModel(TimeStamp, models.Model):
    name = models.CharField(max_length=120)
    description = models.TextField(max_length=500, blank=True, default="")
    products = models.ManyToManyField(ProductModel, blank=True)
    user = models.ForeignKey(USER, on_delete=models.CASCADE, blank=True)

    def __str__(self) -> str:
        return self.name


# ======================================================== #
# Cart Related Models                                      #
# ======================================================== #
class Cart(TimeStamp, models.Model):
    user = models.ForeignKey(USER, on_delete=models.CASCADE)
    empty = models.BooleanField(default=True)
    checked_out = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user}"

    def total(self):
        price = (
            (
                CartItem.objects.filter(cart=self, status=True).annotate(
                    item_price=F("quantity") * F("product__price")
                )
            )
            .aggregate(Sum("item_price"))
            .get("item_price__sum")
        )

        return price

    def items(self):
        cart_items = CartItem.objects.filter(cart__user=self.user, status=True)
        return cart_items

    @staticmethod
    def get_cart(request, **kwargs):
        user = request.user
        cart, created = Cart.objects.get_or_create(
            user=user,
            status=True,
            checked_out=False,
            **kwargs,
        )
        return cart


class CartItem(TimeStamp, models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(ProductModel, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.product} ({self.quantity})"

    def total(self):
        cost = self.product.price * self.quantity
        return cost

    def __iter__(self):
        return self.__next__()

    def __next__(self):
        yield (self.product, self.quantity)


class Order(TimeStamp, models.Model):
    class CurrencyChoices:
        INR = "INR"
        DOLLAR = "D"

    CURRENCY_CHOICES = (
        ("Indian Rupee", CurrencyChoices.INR),
        ("Dollar", CurrencyChoices.DOLLAR),
    )

    id = models.CharField(primary_key=True, unique=True, max_length=120)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    amount = models.FloatField()
    currency = models.CharField(
        max_length=24,
        choices=CURRENCY_CHOICES,
        default=CurrencyChoices.INR,
    )
    delivery_charge = models.FloatField(default=0)
    completed = models.BooleanField(default=False)
    billing_address = models.ForeignKey(
        Address,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="checkout_billing_address",
    )
    shipping_address = models.ForeignKey(
        Address,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,

core/forms.py
from django import forms
from django.contrib.auth import forms as auth_forms
from django.contrib.auth import get_user_model

from core.models import (
    Address,
    Cart,
    CartItem,
    Feedback,
    Order,
    Profile,
    ReviewModel,
    WishlistModel,
)

USER = get_user_model()


class CustomUserCreationForm(auth_forms.UserCreationForm):
    class Meta:
        model = USER
        fields = ["username", "email"]


# Profile form
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = (
            "status",
            "location",
            "address",
            "user",
            "is_loyal",
            "is_active",
            "account_type",
        )


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        exclude = (
            "location",
            "status",
            "created_on",
            "updated_on",
        )


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        exclude = ("is_replied", "status", "user")


class CartItemForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CartItemForm, self).__init__(*args, **kwargs)
        instance = getattr(self, "instance", None)
        if instance and instance.id:
            self.fields["product"].widget = forms.HiddenInput(attrs={})

    class Meta:
        model = CartItem
        fields = ["product", "quantity"]

    def clean_product(self):
        instance = getattr(self, "instance", None)
        if instance:
            return instance.product
        else:
            return self.cleaned_data.get("product", None)


CartItemFormSet = forms.modelformset_factory(
    CartItem, form=CartItemForm, edit_only=True, extra=0, can_delete=True
)

AddressFormSet = forms.modelformset_factory(
    Address, form=AddressForm, edit_only=True, extra=1, can_delete=False
)


class BillingAddressForm(AddressForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.name = "Billing Address"
        self.prefix = "billing"


class ShippingAddressForm(AddressForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.name = "Shipping Address"
        self.prefix = "shipping"


class CurrencyForm(forms.Form):
    INR = Order.CurrencyChoices.INR
    DOLLAR = Order.CurrencyChoices.DOLLAR
    CURRENCY_CHOICES = (
        (INR, "Indian Rupee"),
        (DOLLAR, "Dollar"),
    )
    currency = forms.ChoiceField(choices=CURRENCY_CHOICES, label="")


# Wishlist form
class WishlistForm(forms.ModelForm):
    class Meta:
        model = WishlistModel
        fields = ["name", "description"]


class AddToWishlistForm(forms.ModelForm):
    class Meta:
        model = WishlistModel
        fields = ["name"]


AddToWishlistFormSet = forms.modelformset_factory(
    WishlistModel, form=AddToWishlistForm, edit_only=True, extra=0, can_delete=True
)

# Product Review form
class ProductReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewModel
        fields = ["rating", "comment"]

templates/core/dashboard.html
{% extends 'base.html' %} {% block content %}

<!-- dashboard start -->
<div class="container py-5">
  <div class="row justify-content-center mt-3 mb-3">
    <div class="col-auto">
      <div class="heading-1">
        <h1 class="text-center">Dashboard</h1>
        <div class="hl"></div>
      </div>
    </div>
  </div>

  <div class="row row-cols-auto g-2 g-lg-3 justify-content-center">
    <!-- Items in cart start -->
    <div class="col-auto">
      <a href="{% url 'core:cart' %}">
        <div class="card">
          <div
            class="card-body d-flex flex-column align-items-center justify-content-center text-center h-100"
          >
            <h4 class="mb-2">
              <span class="badge rounded-pill text-bg-primary"
                >{{cart.items.count}}</span
              >
            </h4>
            <h6 class="card-title">Items</h6>
            <p class="card-text">{{category.description}}</p>
          </div>
        </div>
      </a>
    </div>
    <!-- Items in cart end -->

    <!-- Orders start -->
    <div class="col-auto">
      <a href="{% url 'core:order' %}">
        <div class="card">
          <div
            class="card-body d-flex flex-column align-items-center justify-content-center text-center h-100"
          >
            <h4 class="mb-2">
              <span class="badge rounded-pill text-bg-primary"
                >{{orders.count}}</span
              >
            </h4>
            <h6 class="card-title">Orders</h6>
            <p class="card-text">{{category.description}}</p>
          </div>
        </div>
      </a>
    </div>
    <!-- Orders end -->

    <!-- payments start -->
    <div class="col-auto">
      <a href="{% url 'core:payment_list' %}">
        <div class="card">
          <div
            class="card-body d-flex flex-column align-items-center justify-content-center text-center h-100"
          >
            <h4 class="mb-2">
              <span class="badge rounded-pill text-bg-primary"
                >{{payments.count}}</span
              >
            </h4>
            <h6 class="card-title first-letter-danger">Payments</h6>
            <p class="card-text">{{category.description}}</p>
          </div>
        </div>
      </a>
    </div>
    <!-- payments start -->

    <!-- wishlist start -->
    <div class="col-auto">
      <a href="{% url 'core:wishlist_list' %}">
        <div class="card">
          <div
            class="card-body d-flex flex-column align-items-center justify-content-center text-center h-100"
          >
            <h4 class="mb-2">
              <span class="badge rounded-pill text-bg-primary"
                >{{user.wishlistmodel_set.count}}</span
              >
            </h4>
            <h6 class="card-title">Wishlist</h6>
            <p class="card-text">{{category.description}}</p>
          </div>
        </div>
      </a>
    </div>
    <!-- wishlist end -->
    <!-- Order Delivered start -->
    <div class="col-auto">
      <a href="">
        <div class="card">
          <div
            class="card-body d-flex flex-column align-items-center justify-content-center text-center h-100"
          >
            <h4 class="mb-2">
              <span class="badge rounded-pill text-bg-primary">0</span>
            </h4>
            <h6 class="card-title first-letter-danger">
              <a href="" class="link-dark">Order Delivered</a>
            </h6>
            <p class="card-text">{{category.description}}</p>
          </div>
        </div>
      </a>
    </div>
    <!-- Order Delivered end -->
  </div>

  <div class="row">
    <div class="col">
      <a href="{% url 'core:shop' %}" class="btn btn-dark rounded-pill px-4 py-2">Shop</a>
    </div>
  </div>
</div>
<!-- end dashboard -->
{% endblock content %}

templates/core/order.html
{% extends 'base.html' %} {% block content %}

<!-- products -->
<div class="container py-5">
  <div class="row justify-content-center mt-3 mb-3">
    <div class="col-auto">
      <div class="heading-1">
        <h1 class="text-center">Orders</h1>
        <div class="hl"></div>
      </div>
    </div>
  </div>

  <div class="row row-cols-2 row-cols-lg-5 g-2 g-lg-3 justify-content-center">
    {% for order in orders %}

    <div class="col-auto">
      <a href="{% url 'core:order_detail' order.id %}" class="link-dark">
        <div class="card">
          <div class="card-body">
            <h6 class="card-title">{{order.id|upper}}</h6>
            <p class="card-text">INR {{order.amount}}</p>
            <ul>
              {% for item in order.cart.items %}

              <li>{{item}}</li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </a>
    </div>
    {% empty %}
    <h4>Nothing Found!!</h4>
    {% endfor %}
  </div>
</div>
<!-- end products -->
{% endblock content %}

templates/core/paymentfail.html
{% extends 'base.html' %} 

{% block content %}

<h5 class="text-danger">
  Payment failed!
  <span>
    Back to <a href="{% url 'core:home' %}" class="link-primary">home</a>
  </span>
</h5>

{% endblock %}

templates/core/product_detail.html
{% extends 'base.html' %} {% block content %}

<!-- products -->
<div class="container py-5">
  <div class="row justify-content-center mt-3 mb-3">
    <div class="col-auto">
      <div class="heading-1">
        <h1 class="text-center">Product Details</h1>
        <div class="hl"></div>
      </div>
    </div>
  </div>

  <div class="row g-2">
    <div class="col-lg-4">
      <div class="card">
        <div class="card-body">
          <img src="{{product.image.url}}" alt="..." class="card-img" />
        </div>
      </div>
    </div>
    <div class="col-lg-8 px-lg-4">
      <table class="table table-borderless table-hover">
        <thead></thead>
        <tbody>
          <tr>
            <th>Name</th>
            <td>{{product.name}}</td>
          </tr>
          <tr>
            <th>Description</th>
            <td>{{product.description}}</td>
          </tr>
          <tr>
            <th>Price</th>
            <td>INR {{product.price}}</td>
          </tr>
          <tr>
            <th>Category</th>
            <td>{{product.category}}</td>
          </tr>
          <tr class="text-nowrap">
            <th>Last Updated</th>
            <td>{{product.updated_on|date}}</td>
          </tr>
          <tr>
            <th>Rating</th>
            <td>{{product.reviewmodel.rating}}</td>
          </tr>
          <tr>
            <td class="" colspan="2">
              <form action="{% url 'core:cart_add' %}" class="d-inline-block" method="post">
                {% csrf_token %}
                <input type="hidden" name="product_id" value="{{product.id}}" />
                <input type="hidden" name="quantity" value="1" />
                <button
                  type="submit"
                  class="btn btn-primary border-0 rounded-5 py-3 px-4 text-nowrap"
                >
                  <i class="fa-solid fa-shopping-cart"></i> Add to Cart
                </button>
              </form>

              <a
                href="{% url 'core:add_to_wishlist' product.id %}"
                class="btn btn-dark border-0 rounded-5 py-3 px-4"
              >
                <i class="fa-solid fa-heart"></i>
                Add to wishlist
              </a>
              <a
                href="{% url 'core:add_product_review' product.id %}"
                class="btn btn-dark rounded-5 px-4 py-3"
              >
                <i class="fa-solid fa-star"></i>
                Add Review
              </a>
              <a
                href="{% url 'core:shop' %}"
                class="btn btn-dark rounded-5 px-4 py-3"
              >
                <i class="fa-solid fa-arrow-left"></i>
                Shop
              </a>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
<!-- end products -->
{% endblock content %}

templates/core/whishlist_add.html
{% extends 'base.html' %} {% block content %}

<!-- products -->
<div class="container py-5">
  <div class="row justify-content-center mt-3 mb-3">
    <div class="col-auto">
      <div class="heading-1">
        <h1 class="text-center">Add to Whishlist</h1>
        <div class="hl"></div>
      </div>
    </div>
  </div>
  <div class="row g-3">
    <div class="col-lg-6">
      <div class="card">
        <img src="{{product.image.url}}" alt="" class="card-img-top" />
        <div class="card-body">
          <h5 class="card-title">{{product.name}}</h5>
          <p class="card-text">{{product.description}}</p>
        </div>
      </div>
    </div>
    <div class="col-lg-6">
      <form action="" method="post">
        {% csrf_token %}
        <div class="row row-cols-auto g-2 mb-3">
          {% for wishlist in wishlists %}

          <div class="col-auto">
            <div class="card rounded-pill">
              <div class="card-body">
                <div class="form-check d-flex align-items-center justify-content-start">
                  <input
                    class="form-check-input me-2"
                    type="checkbox"
                    name="wishlists"
                    value="{{wishlist.id}}"
                    id="id_wishlist_{{wishlist.id}}"
                    {% if product in wishlist.products.all %}
                    checked="true"
                    {% endif %}
                  />
                  <label class="form-check-label text-nowrap" for="id_wishlist_{{wishlist.id}}">
                    <a href="{% url 'core:wishlist_detail' wishlist.id %}"
                      >{{wishlist.name}}</a
                    >
                  </label>
                </div>
              </div>
            </div>
          </div>

          {% empty %}
          <h5>No wishlist found</h5>
          {% endfor %}
        </div>
        <div class="mb-3">

          <a
          href="{% url 'core:wishlist_create' %}"
          class="btn btn-dark rounded-5 px-4 py-3"
          >Create now</a
          >
        </div>
        <hr>
        <button class="btn btn-primary rounded-5 px-4 py-3 me-2">Update</button>
        <a
          href="{% url 'core:shop' %}"
          class="btn btn-dark rounded-5 px-4 py-3"
          >Shop</a
        >
      </form>
    </div>
  </div>
</div>
<!-- end products -->
{% endblock content %}

templates/core/whishlist_detail.html
{% extends 'base.html' %} {% block content %}

<!-- products -->
<div class="container py-5">
  <div class="row justify-content-center mt-3 mb-3">
    <div class="col-auto">
      <div class="heading-1">
        <h1 class="text-center">Whishlist Details</h1>
        <div class="hl"></div>
      </div>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col">
      <h4 class="d-flex justify-content-between">
        {{wishlist.name}}
        <span class="h5">
          <a href="{% url 'core:shop' %}">Back to shop</a>
        </span>
      </h4>
      <div class="hr"></div>
    </div>
  </div>

  <div class="row product-lists">
    {% for product in wishlist.products.all %}

    <!-- product section -->
    <div class="col-lg-4 col-md-6 text-center">
      <div class="single-product-item">
        <div class="product-image">
          <a href="{% url 'core:product_detail' product.id %}"
            ><img src="{{product.image.url}}" alt=""
          /></a>
        </div>
        <h3>{{product.name}}</h3>
        <p class="product-price">
          <span>Per {{product.unit}}</span>
          <i class="fa-solid fa-inr"></i>
          {{product.price}}
        </p>
        <form action="{% url 'core:cart_add' %}" method="post">
          {% csrf_token %}
          <input type="hidden" name="wishlist_id" value="{{wishlist.id}}" />
          <button
            formaction="{% url 'core:remove_from_wishlist' product.id %}"
            class="btn btn-cart border-0 rounded-5 py-3 px-4"
          >
            <i class="fa-solid fa-trash"></i>
            Remove
          </button>
          <button
            type="submit"
            class="btn btn-cart border-0 rounded-5 py-3 px-4"
          >
            <i class="fa-solid fa-shopping-cart"></i> Add to Cart
          </button>
        </form>
      </div>
    </div>

    {% empty %}

    <div class="col text-center">
      <div class="card rounded-2 border-0">
        <div class="card-body">
          <h3>Nothing found!!</h3>
          <p>
            <a href="{% url 'core:shop' %}">Back to shop</a>
          </p>
        </div>
      </div>
    </div>
    {% endfor %}
    <!-- end product section -->
  </div>

  <div class="row">
    <div class="col-lg-12 text-center">
      <div class="pagination-wrap">
        <ul>
          {% if page_obj.has_previous %}
          <li><a href="?page=1">First</a></li>

          <li>
            <a href="?page={{ page_obj.previous_page_number }}">&laquo; Prev</a>
          </li>

          {% endif %}

          <li>
            <a class="active" href="#">{{ page_obj.number|default:0 }}</a>
          </li>

          {% if page_obj.has_next %}

          <li>
            <a href="?page={{ page_obj.next_page_number }}">&raquo; Next</a>
          </li>
          <li>
            <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </div>
</div>
<!-- end products -->
{% endblock content %}