core/urls.py
from django.urls import path
from core import views

app_name = "core"


urlpatterns = [
    # Common
    path("", views.HomeView.as_view(), name="home"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("contact/", views.ContactView.as_view(), name="contact"),
    path("news/", views.NewsView.as_view(), name="news"),
    path("shop/", views.ShopView.as_view(), name="shop"),
    # User
    path("user/profile/", views.ProfileView.as_view(), name="profile"),
    path("user/dashboard/", views.DashboardView.as_view(), name="dashboard"),
    path("user/settings/", views.SettingsView.as_view(), name="settings"),
    # Authentication urls
    path("user/login/", views.LoginView.as_view(), name="login"),
    path("user/signup/", views.SignupView.as_view(), name="signup"),
    path("user/logout/", views.LogoutView.as_view(), name="logout"),
    # Password Reset
    path("user/password_reset/", views.PasswordResetView.as_view(), name="password_reset"),
    path("user/password_reset/done/", views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("user/reset/<uidb64>/<token>/", views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("user/reset/done/", views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    # Password Change
    path("user/password_change/", views.PasswordChangeView.as_view(), name="password_change"),
    path("user/password_change/done/", views.PasswordChangeDoneView.as_view(), name="password_change_done"),
    # Product
    path("product/<int:pk>/detail/", views.ProductDetailView.as_view(), name="product_detail"),
    path("product/category/", views.CategoryListView.as_view(), name="category_list"),
    path("product/category/<int:pk>/product/", views.ProductListByCategory.as_view(), name="product_by_category"),
    # Product Review
    path("product/<int:pk>/review/", views.ProductReviewAddView.as_view(), name="add_product_review"),
    # Wishlist
    path("wishlist/", views.WishlistListView.as_view(), name="wishlist_list"),
    path("wishlist/create/", views.WishlistCreateView.as_view(), name="wishlist_create"),
    path("wishlist/<int:pk>/", views.WishlistDetailView.as_view(), name="wishlist_detail"),
    path("wishlist/add/product/<int:product_pk>/", views.AddToWishlist.as_view(), name="add_to_wishlist"),
    path("wishlist/remove/product/<int:product_pk>/", views.AddToWishlist.as_view(), name="remove_from_wishlist"),
    # Cart
    path("cart/", views.CartView.as_view(), name="cart"),
    path("cart/add/", views.AddToCartView.as_view(), name="cart_add"),
    path("cart/checkout/", views.CheckoutView.as_view(), name="cart_checkout"),
    path("cart/payment/", views.PaymentView.as_view(), name="cart_payment"),
    # Payment
    path("payment/", views.PaymentListView.as_view(), name="payment_list"),
    # Order
    path("order/history/", views.OrderHistoryView.as_view(), name="order_history"),
    path("order/", views.OrderView.as_view(), name="order"),
    path("order/<str:pk>/", views.OrderDetailView.as_view(), name="order_detail"),

]

emart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path('accounts/', include('allauth.urls')),
    path("admin/", admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/cart_item_listing.html
{% for form in formset %}
<tr class="table-body-row">
  <td class="product-remove">
    <button class="btn border-0">
      <i class="far fa-window-close"></i>
    </button>
  </td>
  <td class="product-image">
    <img src="{{form.instance.product.image.url}}" alt="" />
  </td>
  <td class="product-name">{{form.instance.product}}</td>
  <td class="product-price">INR {{form.instance.product.price}}</td>
  <td class="product-quantity">{{form.quantity}}</td>
  <td class="product-total">INR {{form.instance.total}}</td>
</tr>
{% endfor %}

templates/includes/category_listing.html
{% for category in categories %}

<!-- category section -->
<div class="col-lg-4 col-md-6 text-center">
  <div class="single-product-item">
    <div class="product-image">
      <a href="single-category.html"
        ><img src="{{category.image.url}}" alt=""
      /></a>
    </div>
    <h3>{{category.name}}</h3>
    <p class="product-price">
      <span>Per {{category.unit}}</span>
      <i class="fa-solid fa-inr"></i>
      {{category.price}}
    </p>
    <a href="cart.html" class="cart-btn"
      ><i class="fa-solid fa-shopping-cart"></i> Add to Cart</a
    >
  </div>
</div>

{% empty %}

<div class="col text-center">
  <div class="card rounded-2 border-0">
    <div class="card-body">
      <h3>Nothing found!!</h3>
    </div>
  </div>
</div>
{% endfor %}
<!-- end product section -->

templates/includes/copyright.html
<div class="copyright">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-md-12">
        <p>
          Copyrights &copy; 2022 -
          <a href="https://imransdesign.com/">Jinto A G</a>, All Rights
          Reserved.
        </p>
      </div>
      <div class="col-lg-6 text-right col-md-12">
        <div class="social-icons">
          <ul>
            <li>
              <a href="#" target="_blank"><i class="fab fa-facebook-f"></i></a>
            </li>
            <li>
              <a href="#" target="_blank"><i class="fab fa-twitter"></i></a>
            </li>
            <li>
              <a href="#" target="_blank"><i class="fab fa-instagram"></i></a>
            </li>
            <li>
              <a href="#" target="_blank"><i class="fab fa-linkedin"></i></a>
            </li>
            <li>
              <a href="#" target="_blank"><i class="fab fa-dribbble"></i></a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

templates/includes/footer.html
{% load static %}


<div class="footer-area">
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-6">
        <div class="footer-box about-widget">
          <h2 class="widget-title">About us</h2>
          <p>
            Ut enim ad minim veniam perspiciatis unde omnis iste natus error sit
            voluptatem accusantium doloremque laudantium, totam rem aperiam,
            eaque ipsa quae.
          </p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6">
        <div class="footer-box get-in-touch">
          <h2 class="widget-title">Get in Touch</h2>
          <ul>
            <li>34/8, East Hukupara, Gifirtok, Sadan.</li>
            <li>support@fruitkha.com</li>
            <li>+00 111 222 3333</li>
          </ul>
        </div>
      </div>
      <div class="col-lg-3 col-md-6">
        <div class="footer-box pages">
          <h2 class="widget-title">Pages</h2>
          <ul>
            <li><a href="index.html">Home</a></li>
            <li><a href="about.html">About</a></li>
            <li><a href="services.html">Shop</a></li>
            <li><a href="news.html">News</a></li>
            <li><a href="contact.html">Contact</a></li>
          </ul>
        </div>
      </div>
      <div class="col-lg-3 col-md-6">
        <div class="footer-box subscribe">
          <h2 class="widget-title">Subscribe</h2>
          <p>Subscribe to our mailing list to get the latest updates.</p>
          <form action="index.html">
            <input type="email" placeholder="Email" />
            <button type="submit">
              <i class="fa-solid fa-paper-plane"></i>
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

templates/includes/header.html
{% load static %}
<!-- header start -->
<header class="sticky-top">
  <nav class="navbar navbar-expand-lg bg-dark shadow-sm">
    <div class="container-fluid">
      <a class="navbar-brand text-light" href="#">{{project_name}}</a>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav align-items-lg-center me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a
              class="nav-link active"
              aria-current="page"
              href="{% url 'core:home' %}"
              >Home</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:contact' %}">Contact Us</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:shop' %}">Shop</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:category_list' %}">Categories</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:cart' %}">Cart</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle"
              href="#"
              role="button"
              data-bs-toggle="dropdown"
              aria-expanded="false"
            >
              {{user}}
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'core:profile' %}">Profile</a></li>
              <li><a class="dropdown-item" href="{% url 'core:dashboard' %}">Dashboard</a></li>
              <li><a class="dropdown-item" href="{% url 'core:order_history' %}">Order History</a></li>
              <li><a class="dropdown-item" href="{% url 'core:wishlist_list' %}">Wishlist</a></li>
              <li><a class="dropdown-item" href="{% url 'core:settings' %}">Settings</a></li>
              <li><hr class="dropdown-divider" /></li>
              <li>
                <a class="dropdown-item" href="{% url 'core:logout' %}"
                  >Logout</a
                >
              </li>
            </ul>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:signup' %}">Sign up</a>
          </li>
          {% endif %}

          <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle"
              href="#"
              role="button"
              data-bs-toggle="dropdown"
              aria-expanded="false"
            >
              <div class="d-inline-block position-relative">
                <i class="fa-solid fa-cart-shopping"></i>
                <span
                  class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger"
                >
                  {{cart.items|length|default:"0"}}
                  <span class="visually-hidden">unread messages</span>
                </span>
              </div>
            </a>
            <ul class="dropdown-menu m-0">
              <li class="p-3">
                <table
                  class="table caption-top table-borderless table-striped mb-0 align-middle text-center"
                >
                  <caption>
                    List of Products
                  </caption>

                  <thead class="">
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">Name</th>
                      <th scope="col">Price</th>
                      <th scope="col">Qty</th>
                      <th scope="col">Total</th>
                    </tr>
                  </thead>
                  <tbody class="table-group-divider">
                    {% for item in cart.items %}
                    <tr>
                      <th scope="row">{{forloop.counter}}</th>
                      <td class="text-left text-nowrap">
                        <a class="link-primary" href="{% url 'core:product_detail' item.product.id %}"
                          >{{item.product.name}}</a
                        >
                      </td>
                      <td>{{item.product.price}}</td>
                      <td>{{item.quantity}}</td>
                      <td class="text-right">{{item.total}}</td>
                    </tr>
                    {% empty %}
                    <tr>
                      <td class="text-left" colspan="5">Nothing found!</td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </li>
            </ul>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:cart' %}"> </a>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input
            class="form-control me-2"
            type="search"
            placeholder="Search for products"
            aria-label="Search"
          />
          <button class="btn btn-outline-light" type="submit">
          <i class="fa-solid fa-search"></i>
          </button>
        </form>
      </div>
    </div>
  </nav>
</header>
<!-- header end -->

templates/includes/message.html
{% if messages %}
<div class="messages">
  {% for message in messages %}
  <div
    class="alert {{ message.tags }} alert-dismissible fade show"
    role="alert"
  >
    {{ message }}
    <button
      type="button"
      class="btn-close"
      data-bs-dismiss="alert"
      aria-label="Close"
    ></button>
  </div>
  {% endfor %}
</div>

{% endif %}

templates/includes/news.html
<div class="col-lg-4 col-md-6">
  <div class="single-latest-news">
    <a href="single-news.html"><div class="latest-news-bg news-bg-1"></div></a>
    <div class="news-text-box">
      <h3>
        <a href="single-news.html"
          >You will vainly look for fruit on it in autumn.</a
        >
      </h3>
      <p class="blog-meta">
        <span class="author"><i class="fa-solid fa-user"></i> Admin</span>
        <span class="date"
          ><i class="fa-solid fa-calendar"></i> 27 December, 2019</span
        >
      </p>
      <p class="excerpt">
        Vivamus lacus enim, pulvinar vel nulla sed, scelerisque rhoncus nisi.
        Praesent vitae mattis nunc, egestas viverra eros.
      </p>
      <a href="single-news.html" class="read-more-btn"
        >read more <i class="fa-solid fa-angle-right"></i
      ></a>
    </div>
  </div>
</div>
<div class="col-lg-4 col-md-6">
  <div class="single-latest-news">
    <a href="single-news.html"><div class="latest-news-bg news-bg-2"></div></a>
    <div class="news-text-box">
      <h3>
        <a href="single-news.html"
          >A man's worth has its season, like tomato.</a
        >
      </h3>
      <p class="blog-meta">
        <span class="author"><i class="fa-solid fa-user"></i> Admin</span>
        <span class="date"
          ><i class="fa-solid fa-calendar"></i> 27 December, 2019</span
        >
      </p>
      <p class="excerpt">
        Vivamus lacus enim, pulvinar vel nulla sed, scelerisque rhoncus nisi.
        Praesent vitae mattis nunc, egestas viverra eros.
      </p>
      <a href="single-news.html" class="read-more-btn"
        >read more <i class="fa-solid fa-angle-right"></i
      ></a>
    </div>
  </div>
</div>
<div class="col-lg-4 col-md-6 offset-md-3 offset-lg-0">
  <div class="single-latest-news">
    <a href="single-news.html"><div class="latest-news-bg news-bg-3"></div></a>
    <div class="news-text-box">
      <h3>
        <a href="single-news.html"
          >Good thoughts bear good fresh juicy fruit.</a
        >
      </h3>
      <p class="blog-meta">
        <span class="author"><i class="fa-solid fa-user"></i> Admin</span>
        <span class="date"
          ><i class="fa-solid fa-calendar"></i> 27 December, 2019</span
        >
      </p>
      <p class="excerpt">
        Vivamus lacus enim, pulvinar vel nulla sed, scelerisque rhoncus nisi.
        Praesent vitae mattis nunc, egestas viverra eros.
      </p>
      <a href="single-news.html" class="read-more-btn"
        >read more <i class="fa-solid fa-angle-right"></i
      ></a>
    </div>
  </div>
</div>

templates/includes/product_listing.html
{% for product in products %}

<!-- product section -->
<div class="col-lg-4 col-md-6 text-center">
  <div class="single-product-item">
    <div class="product-image">
      <a href="{% url 'core:product_detail' product.id %}"
        ><img src="{{product.image.url}}" alt=""
      /></a>
    </div>
    <h3>{{product.name}}</h3>
    <p class="product-price">
      <span>Per {{product.unit}}</span>
      <i class="fa-solid fa-inr"></i>
      {{product.price}}
    </p>
    <form action="{% url 'core:cart_add' %}" method="post">
      {% csrf_token %}
      <input type="hidden" name="product_id" value="{{product.id}}" />
      <input type="hidden" name="quantity" value="1" />
      <a
        href="{% url 'core:add_to_wishlist' product.id %}"
        class="btn btn-cart border-0 rounded-5 py-3 px-4"
        >
        <i class="fa-solid fa-heart"></i>
        Add to wishlist
        </a>
      <button type="submit" class="btn btn-cart border-0 rounded-5 py-3 px-4">
        <i class="fa-solid fa-shopping-cart"></i> Add to Cart
      </button>
    </form>
  </div>
</div>

{% empty %}

<div class="col text-center">
  <div class="card rounded-2 border-0">
    <div class="card-body">
      <h3>Nothing found!!</h3>
    </div>
  </div>
</div>
{% endfor %}
<!-- end product section -->

templates/includes/scripts.html
{% load static %}

<!-- jquery -->
<script src="{% static 'theme/assets/js/jquery-1.11.3.min.js' %}"></script>
<!-- Google Recaptcha -->
<script src="https://www.google.com/recaptcha/api.js"></script>
<!-- bootstrap -->
<script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- fontawesome -->
<!-- <script src="{% static 'fontawesome/js/all.min.js' %}"></script> -->
<!-- count down -->
<script src="{% static 'theme/assets/js/jquery.countdown.js' %}"></script>
<!-- isotope -->
<script src="{% static 'theme/assets/js/jquery.isotope-3.0.6.min.js' %}"></script>
<!-- waypoints -->
<script src="{% static 'theme/assets/js/waypoints.js' %}"></script>
<!-- owl carousel -->
<script src="{% static 'theme/assets/js/owl.carousel.min.js' %}"></script>
<!-- magnific popup -->
<script src="{% static 'theme/assets/js/jquery.magnific-popup.min.js' %}"></script>
<!-- mean menu -->
<script src="{% static 'theme/assets/js/jquery.meanmenu.min.js' %}"></script>
<!-- sticker js -->
<script src="{% static 'theme/assets/js/sticker.js' %}"></script>
<!-- main js -->
<script src="{% static 'theme/assets/js/main.js' %}"></script>

<!-- scripts -->
<script src="{% static 'js/utils.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>

templates/includes/search_area.html
<!-- search area -->
<div class="search-area">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <span class="close-btn"><i class="fas fa-window-close"></i></span>
        <div class="search-bar">
          <div class="search-bar-tablecell">
            <h3>Search For:</h3>
            <input type="text" placeholder="Keywords" />
            <button type="submit">Search <i class="fas fa-search"></i></button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- end search arewa -->

templates/includes/styles.html
{% load static %}


<!-- favicon -->
<link rel="shortcut icon" type="image/png" href="{% static 'theme/assets/img/favicon.png' %}">
<!-- google font -->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
<!-- fontawesome -->
<link rel='stylesheet' href="{% static 'fontawesome/css/all.css' %}">
<!-- bootstrap -->
<link rel='stylesheet' href="{% static 'bootstrap/css/bootstrap.css' %}">
<!-- owl carousel -->
<link rel="stylesheet" href="{% static 'theme/assets/css/owl.carousel.css' %}">
<!-- magnific popup -->
<link rel="stylesheet" href="{% static 'theme/assets/css/magnific-popup.css' %}">
<!-- animate css -->
<link rel="stylesheet" href="{% static 'theme/assets/css/animate.css' %}">
<!-- mean menu css -->
<link rel="stylesheet" href="{% static 'theme/assets/css/meanmenu.min.css' %}">
<!-- main style -->
<link rel="stylesheet" href="{% static 'theme/assets/css/main.css' %}">
<!-- responsive -->
<link rel="stylesheet" href="{% static 'theme/assets/css/responsive.css' %}">

<link rel="stylesheet" href="{% static 'css/style.css' %}">

templates/includes/testimonial.html
{% load static %}
<div class="single-testimonial-slider">
  <div class="client-avater">
    <img src="{% static 'theme/assets/img/avaters/avatar1.png' %}" alt="" />
  </div>
  <div class="client-meta">
    <h3>Saira Hakim <span>Local shop owner</span></h3>
    <p class="testimonial-body">
      " Sed ut perspiciatis unde omnis iste natus error veritatis et quasi
      architecto beatae vitae dict eaque ipsa quae ab illo inventore Sed ut
      perspiciatis unde omnis iste natus error sit voluptatem accusantium "
    </p>
    <div class="last-icon">
      <i class="fa-solid fa-quote-right"></i>
    </div>
  </div>
</div>
<div class="single-testimonial-slider">
  <div class="client-avater">
    <img src="{% static 'theme/assets/img/avaters/avatar2.png' %}" alt="" />
  </div>
  <div class="client-meta">
    <h3>David Niph <span>Local shop owner</span></h3>
    <p class="testimonial-body">
      " Sed ut perspiciatis unde omnis iste natus error veritatis et quasi
      architecto beatae vitae dict eaque ipsa quae ab illo inventore Sed ut
      perspiciatis unde omnis iste natus error sit voluptatem accusantium "
    </p>
    <div class="last-icon">
      <i class="fa-solid fa-quote-right"></i>
    </div>
  </div>
</div>
<div class="single-testimonial-slider">
  <div class="client-avater">
    <img src="{% static 'theme/assets/img/avaters/avatar3.png' %}" alt="" />
  </div>
  <div class="client-meta">
    <h3>Jacob Sikim <span>Local shop owner</span></h3>
    <p class="testimonial-body">
      " Sed ut perspiciatis unde omnis iste natus error veritatis et quasi
      architecto beatae vitae dict eaque ipsa quae ab illo inventore Sed ut
      perspiciatis unde omnis iste natus error sit voluptatem accusantium "
    </p>
    <div class="last-icon">
      <i class="fa-solid fa-quote-right"></i>
    </div>
  </div>
</div>

<div class="single-testimonial-slider">
  <div class="client-avater">
    <img src="{% static 'theme/assets/img/avaters/avatar3.png' %}" alt="" />
  </div>
  <div class="client-meta">
    <h3>Jacob Sikim <span>Local shop owner</span></h3>
    <p class="testimonial-body">
      " Sed ut perspiciatis unde omnis iste natus error veritatis et quasi
      architecto beatae vitae dict eaque ipsa quae ab illo inventore Sed ut
      perspiciatis unde omnis iste natus error sit voluptatem accusantium "
    </p>
    <div class="last-icon">
      <i class="fa-solid fa-quote-right"></i>
    </div>
  </div>
</div>
<div class="single-testimonial-slider">
  <div class="client-avater">
    <img src="{% static 'theme/assets/img/avaters/avatar3.png' %}" alt="" />
  </div>
  <div class="client-meta">
    <h3>Jacob Sikim <span>Local shop owner</span></h3>
    <p class="testimonial-body">
      " Sed ut perspiciatis unde omnis iste natus error veritatis et quasi
      architecto beatae vitae dict eaque ipsa quae ab illo inventore Sed ut
      perspiciatis unde omnis iste natus error sit voluptatem accusantium "
    </p>
    <div class="last-icon">
      <i class="fa-solid fa-quote-right"></i>
    </div>
  </div>
</div>